[package]
name = "main"
version = "0.1.0"
authors = ["shieber"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
hash = { path = "../hash" }
